# coding: UTF-8
from collections import OrderedDict
lang_trans = OrderedDict(
    [
     ('class','クラス'),
     ('cap-shape','かさ形状'),
     ('cap-surface','かさ表面'),
     ('cap-color','かさ色'),
     ('bruises','きず'),
     ('odor','におい'),
     ('gill-attachment','ひだのつき方'),
     ('gill-spacing','ひだ間隔'),
     ('gill-size','ひだサイズ'),
     ('gill-color','ひだ色'),
     ('stalk-shape','柄形状'),
     ('stalk-root','柄根本'),
     ('stalk-surface-above-ring','柄表面(つば上方)'),
     ('stalk-surface-below-ring','柄表面(つば下方)'),
     ('stalk-color-above-ring','柄色(つば上方)'),
     ('stalk-color-below-ring','柄色(つば下方)'),
     ('veil-type','つぼタイプ'),
     ('veil-color','つぼ色'),
     ('ring-number','つば数'),
     ('ring-type','つばタイプ'),
     ('spore-print-color','胞子紋色'),
     ('population','集団形成'),
     ('habitat','生息地')
    ]
)
data_items = OrderedDict(
    [
     ('class',
          OrderedDict(
                    [
                     ('e','食用'),
                     ('p','毒')
                    ]
          )          
     ),
     ('cap-shape',
          OrderedDict(
                    [
                     ('b','ベル'),
                     ('c','円錐'),
                     ('x','饅頭'),
                     ('f','扁平'),
                     ('k','こぶ'),
                     ('s','凹')
                    ]
          )          
     ),
     ('cap-surface',
          OrderedDict(
                    [
                     ('f','繊維'),
                     ('g','溝'),
                     ('y','鱗片'),
                     ('s','平滑')
                    ]
          )          
     ),
     ('cap-color',
          OrderedDict(
                    [
                     ('n','茶'),
                     ('b','淡黄'),
                     ('c','シナモン'),
                     ('g','灰'),
                     ('r','緑'),
                     ('p','桃'),
                     ('u','紫'),
                     ('e','赤')
                    ]
          )          
     ),
     ('bruises',
          OrderedDict(
                    [
                     ('t','有'),
                     ('f','無')
                    ]
          )          
     ),
     ('odor',
          OrderedDict(
                    [
                     ('a','アーモンド'),
                     ('l','アニス'),
                     ('c','クレオソート'),
                     ('y','魚'),
                     ('f','悪'),
                     ('m','かび'),
                     ('n','無'),
                     ('p','刺激'),
                     ('s','スパイシー',)
                    ]
          )          
     ),
     ('gill-attachment',
          OrderedDict(
                    [
                     ('a','直'),
                     ('d','垂'),
                     ('f','離'),
                     ('n','湾')
                    ]
          )          
     ),
     ('gill-spacing',
          OrderedDict(
                    [
                     ('c','近'),
                     ('w','密'),
                     ('d','遠')
                    ]
          )          
     ),
     ('gill-size',
          OrderedDict(
                    [
                     ('b','広'),
                     ('n','狭')
                    ]
          )          
     ),
     ('gill-color',
          OrderedDict(
                    [
                     ('k','黒'),
                     ('n','茶'),
                     ('b','淡黄'),
                     ('h','チョコレート'),
                     ('g','灰'),
                     ('r','緑'),
                     ('o','橙'),
                     ('p','桃'),
                     ('u','紫'),
                     ('e','赤'),
                     ('w','白'),
                     ('y','黄')
                    ]
          )          
     ),
     ('stalk-shape',
          OrderedDict(
                    [
                     ('e','先太'),
                     ('t','先細')
                    ]
          )          
     ),
     ('stalk-root',
          OrderedDict(
                    [
                     ('b','球根'),
                     ('c','棍棒'),
                     ('u','カップ'),
                     ('e','扁平'),
                     ('z','根状菌糸束'),
                     ('r','根'),
                     ('?','欠測')
                    ]
          )          
     ),
     ('stalk-surface-above-ring',
          OrderedDict(
                    [
                     ('f','繊維'),
                     ('y','鱗片'),
                     ('k','絹'),
                     ('s','平滑')
                    ]
          )          
     ),
     ('stalk-surface-below-ring',
          OrderedDict(
                    [
                     ('f','繊維'),
                     ('y','鱗片'),
                     ('k','絹'),
                     ('s','平滑')
                    ]
          )          
     ),
     ('stalk-color-above-ring',
          OrderedDict(
                    [
                     ('n','茶'),
                     ('b','淡黄'),
                     ('c','シナモン'),
                     ('g','灰'),
                     ('o','橙'),
                     ('p','桃'),
                     ('e','赤'),
                     ('w','白'),
                     ('y','黄')
                    ]
          )          
     ),
     ('stalk-color-below-ring',
          OrderedDict(
                    [
                     ('n','茶'),
                     ('b','淡黄'),
                     ('c','シナモン'),
                     ('g','灰'),
                     ('o','橙'),
                     ('p','桃'),
                     ('e','赤'),
                     ('w','白'),
                     ('y','黄')
                    ]
          )          
     ),
     ('veil-type',
          OrderedDict(
                    [
                     ('p','部分'),
                     ('u','全体')
                    ]
          )          
     ),
     ('veil-color',
          OrderedDict(
                    [
                     ('n','茶'),
                     ('o','橙'),
                     ('w','白'),
                     ('y','黄')
                    ]
          )          
     ),
     ('ring-number',
          OrderedDict(
                    [
                     ('n','０'),
                     ('o','１'),
                     ('t','２')
                    ]
          )          
     ),
     ('ring-type',
          OrderedDict(
                    [
                     ('c','クモの巣'),
                     ('e','一過'),
                     ('f','口広がり'),
                     ('l','大'),
                     ('n','無'),
                     ('p','ペンダント'),
                     ('s','被覆'),
                     ('z','ゾーン')
                    ]
          )          
     ),
     ('spore-print-color',
          OrderedDict(
                    [
                     ('k','黒'),
                     ('n','茶'),
                     ('b','淡黄'),
                     ('h','チョコレート'),
                     ('r','緑'),
                     ('o','橙'),
                     ('u','紫'),
                     ('w','白'),
                     ('y','黄')
                    ]
          )          
     ),
     ('population',
          OrderedDict(
                    [
                     ('a','豊富'),
                     ('c','群生'),
                     ('n','多数'),
                     ('s','散在'),
                     ('v','少数'),
                     ('y','単性')
                    ]
          )          
     ),
     ('habitat',
          OrderedDict(
                    [
                     ('g','芝生'),
                     ('l','葉'),
                     ('m','牧草地'),
                     ('p','道路'),
                     ('u','都市部'),
                     ('w','廃棄物'),
                     ('d','木')
                    ]
          )
     )
    ]
)


